### ISSUE TITLE
Fix undefined on message when displaying the PORT number

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/twitch#16]
🚀  Server ready at `undefined`

**Comment by fernandovfilho** [comment]
This message is because you need to rename .env.example to .env to set the environment var PORT, this file is used by dotenv package to set environments vars and in Heroku they set var PORT for you automatically because there you are in a shared environment and they choose the port.

In resume this file is like local.properties in a Android project.

**Comment by AlderFurtado** [comment]
If you use Heroku, sometimes, you need set in heroku the enviroment variables 

To fix that, go in settings, Config Vars and add the variables

I hope that help :)
